# Generated by Django 5.2.14 on 2026-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_label', models.CharField(default='About', max_length=40)),
                ('heading', models.CharField(default='Engineering premium products from concept to scale.', max_length=255)),
                (
                    'description',
                    models.TextField(
                        default='I specialize in end-to-end product engineering across React frontends and Django APIs. My focus is reliability, refined visual systems, and maintainable architecture that supports fast iteration.'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='dynamic', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['category', 'order', '-featured', '-created_at']},
        ),
    ]
