# Generated by Django 5.2.14 on 2026-05-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutsection_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
