# Generated by Django 5.2.14 on 2026-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_herosection_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='herosection',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='herosection',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
