# Generated by Django 5.2.14 on 2026-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_herosection_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_file',
            field=models.FileField(blank=True, null=True, upload_to='skill-icons/'),
        ),
    ]
